
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kshitij
 */
public class mainTapal extends javax.swing.JFrame {

    /**
     * Creates new form mainTapal
     */
    public mainTapal() {
        this.getContentPane().setBackground(Color.decode("#0099FF"));
        this.setUndecorated(false);
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_list = new javax.swing.JButton();
        btn_mng = new javax.swing.JButton();
        btn_ex = new javax.swing.JButton();
        btn_cr = new javax.swing.JButton();
        Post_start = new javax.swing.JButton();
        Post_Stop = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lst_user = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAPAL Manager");
        setBackground(new java.awt.Color(82, 201, 72));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        btn_list.setBackground(new java.awt.Color(237, 195, 105));
        btn_list.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        btn_list.setForeground(new java.awt.Color(1, 1, 1));
        btn_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list-1.png"))); // NOI18N
        btn_list.setText("List Instance");
        btn_list.setFocusable(false);
        btn_list.setName(""); // NOI18N
        btn_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listActionPerformed(evt);
            }
        });

        btn_mng.setBackground(new java.awt.Color(237, 195, 105));
        btn_mng.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        btn_mng.setForeground(new java.awt.Color(1, 1, 1));
        btn_mng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file165.png"))); // NOI18N
        btn_mng.setText("Manage Instances");
        btn_mng.setFocusable(false);
        btn_mng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mngActionPerformed(evt);
            }
        });

        btn_ex.setBackground(new java.awt.Color(205, 81, 51));
        btn_ex.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        btn_ex.setForeground(new java.awt.Color(1, 1, 1));
        btn_ex.setText("Exit");
        btn_ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exActionPerformed(evt);
            }
        });

        btn_cr.setBackground(new java.awt.Color(237, 195, 105));
        btn_cr.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        btn_cr.setForeground(new java.awt.Color(1, 1, 1));
        btn_cr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create3.png"))); // NOI18N
        btn_cr.setText("Create Instance");
        btn_cr.setFocusable(false);
        btn_cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crActionPerformed(evt);
            }
        });

        Post_start.setBackground(new java.awt.Color(237, 195, 105));
        Post_start.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        Post_start.setForeground(new java.awt.Color(1, 1, 1));
        Post_start.setText("Postfix Start");
        Post_start.setFocusable(false);
        Post_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Post_startActionPerformed(evt);
            }
        });

        Post_Stop.setBackground(new java.awt.Color(237, 195, 105));
        Post_Stop.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        Post_Stop.setForeground(new java.awt.Color(1, 1, 1));
        Post_Stop.setText("Postfix Stop");
        Post_Stop.setFocusable(false);
        Post_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Post_StopActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(237, 195, 105));
        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setText("Add User");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(237, 195, 105));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 1, 1));
        jButton2.setText("Delete User");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel3.setText("Tapal Manager");

        lst_user.setBackground(new java.awt.Color(237, 195, 105));
        lst_user.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        lst_user.setForeground(new java.awt.Color(1, 1, 1));
        lst_user.setText("List Users");
        lst_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lst_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(331, 331, 331))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lst_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_list, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mng, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cr, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Post_start, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Post_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(btn_ex, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Post_start, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_list, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Post_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lst_user, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_ex)
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listActionPerformed
        System.out.println("List of Instances\n");
        try
        {
            Process p=Runtime.getRuntime().exec("postmulti -l");
            p.waitFor();
            BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line=reader.readLine();
            while(line!=null)
            {
                System.out.println(line);
                line=reader.readLine();
            }
        }
        catch(  IOException | InterruptedException e1) {}
        System.out.println("End of List");

    }//GEN-LAST:event_btn_listActionPerformed

    private void btn_mngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mngActionPerformed
        mngTapal a=new mngTapal();
        this.dispose();
        a.setVisible(true);

    }//GEN-LAST:event_btn_mngActionPerformed

    private void btn_exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exActionPerformed
        System.exit(2);
    }//GEN-LAST:event_btn_exActionPerformed

    private void btn_crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crActionPerformed
        createTapal a=new createTapal();
        this.dispose();
        a.setVisible(true);

    }//GEN-LAST:event_btn_crActionPerformed

    private void Post_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Post_startActionPerformed
       
        
// TODO add your handling code here:
        String cmd="postfix start";
          //EXECUTING BASH COMMAND Enable AN INSTANCE
        try
        {
            Process p5=Runtime.getRuntime().exec(cmd);
            p5.waitFor();
            BufferedReader reader=new BufferedReader(new InputStreamReader(p5.getInputStream()));
            String line=reader.readLine();
            while(line!=null)
            {
                System.out.println(line);
                line=reader.readLine();
            }

        }
        catch(IOException | InterruptedException e1) {}
        System.out.println("Postfix Mail System Running..");
        System.out.println("Done");


    }//GEN-LAST:event_Post_startActionPerformed

    private void Post_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Post_StopActionPerformed
        
        String cmd="postfix stop";
          //EXECUTING BASH COMMAND Enable AN INSTANCE
        try
        {
            Process p5=Runtime.getRuntime().exec(cmd);
            p5.waitFor();
            BufferedReader reader=new BufferedReader(new InputStreamReader(p5.getInputStream()));
            String line=reader.readLine();
            while(line!=null)
            {
                System.out.println(line);
                line=reader.readLine();
            }

        }
        catch(IOException | InterruptedException e1) {}
         System.out.println("Postfix mail system is not running ");
        System.out.println("Done");
    }//GEN-LAST:event_Post_StopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        AddUser a=new AddUser();
        this.dispose();
        a.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      DeleteUser a=new DeleteUser();
      this.dispose();
      a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lst_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lst_userActionPerformed
       String cmd2="cut -d: -f1 /etc/passwd";
            System.out.println("List of users\n");    
                try
        {
            Process p0=Runtime.getRuntime().exec(cmd2);
            p0.waitFor();
            BufferedReader reader=new BufferedReader(new InputStreamReader(p0.getInputStream()));
            String line=reader.readLine();
            while(line!=null)
            {
                System.out.println(line);
                line=reader.readLine();
            }

        }
        catch(IOException | InterruptedException e1) {}

                System.out.println("End of List\n");
    }//GEN-LAST:event_lst_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainTapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainTapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainTapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainTapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainTapal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Post_Stop;
    private javax.swing.JButton Post_start;
    private javax.swing.JButton btn_cr;
    private javax.swing.JButton btn_ex;
    private javax.swing.JButton btn_list;
    private javax.swing.JButton btn_mng;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lst_user;
    // End of variables declaration//GEN-END:variables
}
